FROM php:7.0-apache

RUN apt-get update

# necessary packages from apt repo
RUN apt-get install -y vim libmcrypt-dev libmagickwand-dev libmagickcore-dev curl zip unzip

# need to make sure we have these necessary craft extensions
RUN docker-php-ext-install pdo_mysql mcrypt pdo zip
RUN pecl install imagick-3.4.3
RUN docker-php-ext-enable imagick

# node/npm setup
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get install nodejs
RUN nodejs -v node -v npm -v

# enables mod_rewrite
RUN a2enmod rewrite

WORKDIR /var/www

# set up composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && php composer-setup.php && php -r "unlink('composer-setup.php');" && mv composer.phar /usr/local/bin/composer

# use composer to install craft 3
RUN composer create-project -s RC craftcms/craft /var/www
RUN mv /var/www/web /var/www/html
